### PR TITLE
Add keyfile

### PR DESCRIPTION
**Pull request by thatnerdjosh**

### CODE REVIEW

**Comment by nicolai86** [comment]
Looks good hope I can merge it tomorrow after some testing. Thanks for the PR!

**Comment by NerdsvilleCEO** [comment]
No prob

**Comment by nicolai86** [comment]
@NerdsvilleCEO thanks for the PR. I only needed to add a default for compatability with people not having key_file set.

**Comment by thatnerdjosh** [comment]
Ah yes, that is correct :) thank you :D

**Pull request merged**
